# LIST 2 DIMENSI

In [ ]:
List 2 dimensi termasuk dalam list multi dimensi. 
Biasanya digunakan untuk menyimpan struktur data yang kompleks seperti tabel, matriks, grapfik, tree.

In [ ]:
#Contoh list 2 dimensi, yaitu list makanan:
list_makanan= [
    ['seblak','pink tempong','keripik kentang'],
    ['salad buah','kacang','semangka'],
    ['es campur','es kepal', 'es cincau']
]
#Cara mengakses list multidimensi 
print (list_makanan[1]) #untuk memanggil baris ke-1
print (list_makanan[1][2])  #untuk memanggil elemen list dari baris pertama kolom kedua, yaitu semangka
print (list_makanan [1][2]+'dan'+list_makanan [1][1])#memanggil 2 elemen list multidimensi yang berbeda

#mencetak suatu kalimat dengan memanggil elemen pada baris ke-0
print ('Makanan berikut adalah makanan favorit saya '+ str(list_makanan[0]))
#mencetak suatu kalimat dengan memanggil elemen pada baris ke-1
print ('Makanan berikut tergolong makanan yang sehat '+str (list_makanan[1])) 
#mencetak suatu kalimat dengan memanggil elemen pada baris ke-2
print ('Makanan berikut adalah makanan yang cocok untuk berbuka puasa '+str(list_makanan[2])) 



In [ ]:
#memanggil semua elemen yang ada dalam matriks satu per satu 
for menu in list_makanan:
    for makanan in menu:
        print (makanan)

In [ ]:
#mengganti elemen pada kolom dan baris tertentu dengan elemen lain
list_makanan [2][1]= 'sop buah'
print (list_makanan[2][1]) #maka elemen pada baris ke-2 dan kolom pertama dari 'es kepal' menjadi 'sop buah'

#maka pada saat mencetak kembali list tersebut, list yang muncul adalh list yang sudah update dengan perubahan elemen 
#yang dilakukan sebelumnya
print (list_makanan)

In [ ]:
#pemanggilan list matriks yang sudah final, yaitu list_makanan
list_makanan

In [ ]:
#CONTOH LIST MATRIKS 2

#kolom adalah baris yang horizontal, sedangkan baris adalah baris yang vertikal
#menuliskan angka sebagai elemen pada matriks
matrik=[
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
print (matrik)

In [ ]:
#memanggil elemen ada matriks yang ada pada baris pertama
print (matrik[1])

#memanggil elemen pada baris pertama dan kolom kedua
print (matrik [1][2])

#memanggil elemen pada baris kedua
print (matrik [2])

#memanggil elemen matriks yang berada pada baris 0 hingga 2
matrik [0:2]

#mengganti elemen pada baris pertama kolom kedua dengan elemen lain yaitu angka 100
matrik[1][2]=100
print (matrik[1][2]) #mencetak hasilnya

#mengganti elemen pada baris kedua kolom ketiga dengan elemen lain yaitu angka 22
matrik[2][3]=22
print (matrik[2][3]) #mencetak hasilnya

#sehingga setelah mengganti beberapa elemen di atas, maka matriks akan menjadi sbb:
print (matrik)

In [ ]:
#menggabungkan elemen matrik baris ke0 sampai ke2 dan elemen matrik baris ke-1
print (matrik [0:2]+matrik [1])

#menulis elemen yang ada pada baris ke-1 sebanyak 2 kali
print (matrik[1]*2)

#elemen baris ke0 kolom kedua ditambah dengan angka 2
print (matrik [0][2]+2)

#menggabungkan hasil elemen matriks yang dijumlahkan dengan 2 sebelumnya dengan elemen matriks pada baris ke-1
print ('Angka favorit saya adalah sbb '+ str (matrik[0][2])+ str (matrik[1]))

In [ ]:
#CONTOH LIST 2 DIMENSI 3

#penulisan yang tiap barisnya ditulis secara mendatar
matrik_29=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
print (matrik_29)
#ternyata matriks juga dapat ditulis secara horizontal

#memanggil elemen pada matrik_29 pada baris ke-2
print (matrik_29[2])

#memanggil elemen pada matrik_29 pada baris ke-2 kolom ke-1
print (matrik_29[2][1])

In [ ]:
#mencetak baris dan mencetak kolom yang ada dalam baris
for baris in matrik: #mencetak tiap elemen pada baris
    print(baris)
    for kolom in baris: #setelah berhasilmencetak baris tsb, elemen-elem yang ada di baris tsb diprint satu per satu 
                        #secara menurun atau vertikal
        print (kolom)
        
        #lalu sistem akan terus dijalankan sampai elemen yang ada pada baris terakhir telah dicetak
        
        
        
#sama dengan proses sebelumnya, namun kolom diganti baris, dan baris juga diganti dengan kolom.
for kolom in matrik:
    print(kolom)
    for baris in kolom:
        print (baris)

# TUPLES

In [ ]:
Tuple adalah tipe data di phyton yang tidak dapat diubah atau dimodifikasi lagi. 
Tipe data tuple bersifat terurut.
Tipe data ini dapat diakses menggunakan indeks.

In [7]:
#CONTOH TIPE DATA TUPLE

#tipe data tuple membolehkan adanya elemen yang double dalam satu tuple, cntohnya di sini adalah angka 1
angka=(0,1,1,3,4,5)  #tipe data tuple tidak menggunakan kurung siku, melainkan kurung biasa
print (angka) #mencetak semua elemen yang ada di tuple
print (angka[0]) #memanggil elemen ke-0
print (angka[0:3]) #memanggil elemen ke0 sampai ke3


#untuk semua elemen dalam list yaitu elemen 0 sampai 3, akan dicetak satu per satu
for isi in angka [0:3]:
    print (isi)

(0, 1, 1, 3, 4, 5)
0
(0, 1, 1)
0
1
1


In [ ]:
#Berikut adalah bukti bahwa perintah di bawah ini tidak dapat dijalankan karena 
#sifat tuple yang tidak dapat dimodifikasi

print (angka [0]=10) #mengganti elemen tertentu dengan elemen lain

print (angka.append(10))#menambahkan elemen

print (angka.remove(5)) #menghilangkan suatu elemen

#jika tuple dapat diubah ataupun dimodifikasi, maka kemungkinan ada kesalahan dalam membuat kode prorgramnya

In [8]:
#Berikut adalah perintah yang dapat dijalankan pada tipe data tuple

#Contoh tuple yang digunakan:
angka=(0,1,1,3,4,5)

#menghitung berapa banyak angka  1 yang terkandung dalam tuple
print (angka.count (1)) 

#memberi tahu index suatu elemen, di sini adalah index elemen ke-3 pada tuple 
print (angka.index(3)) 

#Mencetak berapa banyak elemen yang ada dalam tuple
print (len(angka))

2
3
6


In [5]:
#mencoba meletakkan angka 3 sebanyak 2 kali, mencari tau di index manakah angka3 akan ditulis
angka=(1,2,3,3,4,4,5,5,5) #angka 3 diletakkan pada elemen ke2 dan 3
angka.index (3) #index elemen angka 3 yang diprint adalah yang lebih awal

2

In [6]:
#mencoba meletakkan angka dengan letak yang lebih berjauhan yaitu salahh satu elemennya di belakang
angka=(1,3,2,4,5,3) 
angka.index(3) #namun tetap elemen yang paling awal lah yang indexnya akan ditulis

1

In [33]:
#Membuat tuple namun isinya hanyalah 1 elemen
buah=('apel',) ##untuk membuat tuple berelemen satu, kita harus meletakkan koma setelahnya agar phyton dapat mengenali
                #bahwa ini adalah sebuah tuple
print (type (buah))  #dikenali sebagai tuple

#membuat repetisi dengan tuple berelemen 1
test= buah*4 #isi pada tuple buah akan mengelami repetisi sebanyak 4 kali
print (test)

#contoh bukan tuple
anjing =('bearnice') #tanpa meletakkan koma
print (type(anjing)) #dikenali sebagai tipe data string



<class 'tuple'>
('apel', 'apel', 'apel', 'apel')
<class 'str'>


In [19]:
#TUPLE DAPAT BERUPA BERBAGAI MACAM TIPE DATA:
#di antaranya ada string, int, bool

tuple_1=('apel','pisang','durian')
print (type(tuple_1))

tuple_2= (1,2,3,4,5,6,7,8,9,0)
print (type(tuple_2))

tuple_3=(True, False, False)
print (type(tuple_3))

#semua terbukti merupakan tipe data tuple

<class 'tuple'>
<class 'tuple'>
<class 'tuple'>


In [20]:
#sebuah tuple dapat memuat berbagai macam tipe data sekaligus.
contoh=( False, "nana",123, "True", True, 1)#menggabungkan tipe data bool, string, dan int secara bersamaan
print (type(contoh)) #dikenali sebagai tuple

<class 'tuple'>


In [22]:
#kita juga dapat menggunakan pembangun tuple () untuk membuat sebuah tuple.
tuple_29= tuple(("makan","minum","tidur"))  #gunakan double kurung
print (tuple_29)

('makan', 'minum', 'tidur')


In [27]:
#cara mengakses nilai tuple
#gunakan kurung siku untuk mengiris beserta indeks untuk mendapatkan nilai yang tersedia pada indeks tsb.
tuple_1=('apel','pisang','durian')
tuple_2= (1,2,3,4,5,6,7,8,9,0)

print ("tuple_1[0]: ", tuple_1[0]) #memanggil elemen ke-0 pada tuple 1 dan menambahkan kalimat pendukung
print ("tuple_2 [1]",tuple_2[1]) #memanggil elemen ke-1 pada tuple 2 dan menambahkan kalimat pendukung

tuple_1[0]:  apel
tuple_2 [1] 2


In [28]:
#UPDATE NILAI DALAM TUPLE PHYTON

contoh_1=(12,34,56,78,90)
contoh_2=('abc','efg','hij')
#Karena nilai tuple tidak dapat diubah atau dimodifikasi, maka buatlah tuple baru seperti berikut:
#tuple yang baru adalah tuple yang menggabungkan kedua tuple sebelumnya
contoh_3= contoh_1+contoh_2
print (contoh_3)

(12, 34, 56, 78, 90, 'abc', 'efg', 'hij')


In [32]:
#HAPUS NILAI DALAM TUPLE PHYTON
#karena pada tuple tidak memungkinkan untuk menghapus elemennya, maka bisa melakukan dengan cara mengggabungkan
#tuple lain dengan unsur-unsur yang tidak ingin dibuang
pelajaran= ('fisika','matematika','kimia')
print (pelajaran)

#hapus tuple dengan statement del (delete)
del pelajaran

#lalu kembali buat tuple yang baru yaitu dengan elemen-elemen yang diinginkan
pelajaran=('geometri analitik','algoritma dan struktur data','aljabar linear elementer')#deklarasi elemen baru
print ('Setelah menggunakan statement del pada tuple, hasilnya: ', pelajaran) #hasilnya akan diupdate dengan  elemen yang baru

('fisika', 'matematika', 'kimia')
Setelah menggunakan statement del pada tuple, hasilnya:  ('geometri analitik', 'algoritma dan struktur data', 'aljabar linear elementer')


In [38]:
#FUNGSI BUILD IN PADA TUPLE PHYTON

nilai= (78,89,97,94,85)
print (max (nilai)) #Mencetak elemen dari tuple yang merupakan nilai maksimum

print (len (nilai)) #Mencetak total anggota dai tuple

print (min(nilai)) #Mencetak elemen tuple yang merupakan nilai minimum


97
5
78


# DICTIONARIES

In [ ]:
Dictionaries digunakan jika datanya terkait satu sama lain.
Misalnya data sesorang yang terdiri dari data umur, nama, tanggal lahir yang merupakan satu kesatuan
data yang bersumber dari orang tersebut.

In [11]:
#membuat sebuah dictionary data seseorang berupa nama, umur, dan statusnya
data_orang={
    "nama": "Ketut Dogler",
    "umur":12,
    "apakah single?":False
}

print (data_orang) #mencetak seluruh data yang ada
print (data_orang['nama']) #mencetak data "nama" dari data sesorang yang sudah dideklarasikan sebelumnya
print (data_orang ['umur']) #mencetak umur dari orang tersebut
print (data_orang ['apakah single?']) #mencetak apakah sesorang tsb single

print (data_orang.get('nama')) #mencari data "nama" dan mencetak nilai tersebut
print (data_orang. get ('umur'))#mencari data "umur" dan mencetak nilai tersebut
print (data_orang.get('apakah single?'))#mencari data "apakah single?" dan mencetak nilai tersebut

#contoh yang salah
print (data_orang['Nama']) #error, karena pada data orang terebut yang dideklarasikan adalah "nama" bukan "Nama"
                            #sehingga akan menghasilkan error karena data tsb tidak ditemukan
print (data_orang ['Umur']) #data yang benar adalah "umur", bukan "Umur" sehingga hasilny error
print (data_orang['apakah singleee?'])  #data yang benar adalah "apakah single?" sehingga hasil akan error

{'nama': 'Ketut Dogler', 'umur': 12, 'apakah single?': False}
Ketut Dogler
12
False
Ketut Dogler
12
False


In [16]:
#FUNGSI GET DARI CONTOH 'DATA ORANG'

 #jika terdapat data "nama", maka hasil yang keluar adalah nilai dari 'nama'.
print (data_orang.get('nama')) #

 #jika terdapat data "apakah single?", maka hasil yang keluar adalah nilai dari 'apakah single.'
print (data_orang.get('apakah single?'))

 #jika terdapat data "umur", maka hasil yang keluar adalah nilai dari umur
print (data_orang.get ('umur'))


#jika menggunakan fungsi get, lalu mencari sebuah kata yang tidak ada dalam data tsb
#hasil yang keluar adalah "None"
print (data_orang.get('Nama'))
print (data_orang.get('apakah taken?'))
print (data_orang.get('umurnya'))
print (data_orang.get('tanggal_lahir'))

Ketut Dogler
False
12
None
None
None


In [17]:
#menambahkan data No HP pada data yang sudah ada sebelumnya
data_orang['HP']='08123456789'
print (data_orang["HP"])

#mencetak hasil data_orang yang sudah diupdat dengan data no HP
print (data_orang)

In [32]:
#LENGTH OF DICTIONARY
# untuk menentukan berapa banyak elemen yang dipunya seuah dicitonary, gunakan fungsi len()
data_orang={
    "nama": "Ketut Dogler",
    "umur":12,
    "apakah single?":False
}

print (len (data_orang))

3


In [31]:
#DICTIONARY ITEM'S DATA TYPE
# elemen dari dictionary bisa berupa beberapa tipe data
data_orang={
    "nama": "Ketut Dogler",
    "umur":12,
    "apakah single?":False
}
print (type (data_orang))

<class 'dict'>


In [33]:
#MEMBUAT SEBUAH DICTIONARY YANG KOSONG
dict =()
print ("Dictionary yang kosong adalah ") 
print (dict) #mencetak hasil dari dictionary yang kosong

Dictionary yang kosong adalah 
()


# LATIHAN: Buatlah program untuk merubah nomor HP yang tadinya berupa angka menjadi sebutan bilangan tersebut. Misalnya angka 0812 akan menjadi nol delapan 1 dua

In [21]:
#membuat nilai tiap angka 1-9 menjadi bentuk tulisan
angka={
    "0":"nol",
    "1":"satu",
    "2":"dua",
    "3":"tiga",
    "4":"empat",
    "5":"lima",
    "6":"enam",
    "7":"tujuh",
    "8":"delapan",
    "9":"sembilan"
}
nomor_hp= input ("Masukkan no HP Anda= ") #no hp akan diinput
nomor_angka=""
for isi in nomor_hp:   #untuk setiap elemen yang ada di no hp harus menjalankan sitem sbb
    nomor_angka+= angka.get (isi)+" "  
print (nomor_angka)  #cetak hasilnya

Masukkan no HP Anda= 085888160897
nol delapan lima delapan delapan delapan satu enam nol delapan sembilan tujuh 


# FUNGSI DALAM PHYTON 

In [ ]:
Kita telah menggunakan beberapa jenis fungsi pada phyton, seperti input, print, len, range,dll.
Fungsi tersebut dibentuk untuk menghindari perulangan pembuatan program secara manual.
Jadi, untuk mempermudah program yang dibuat, setiap fungsi yang kita butuhkan dapat dipanggil

In [36]:
#CONTOH 1

def full_name(first_name,last_name):
    print (f"Nama lengkapnya adalah {first_name} {last_name}")
    
full_name(first_name,last_name) #kita dapat memanggil fungsinya dengan cara seperti ini


#CONTOH LAIN
first_name=input ("Nama depannya adalah ") #menginput nama depan
last_name=input ("Nama belakang adalah ") #menginput nama belakang
full_name=(first_name,last_name)  #membuat variabel full name dengan menggabungkan kedua variabel sebelumnya
print (full_name) #cetak hasilnya

Nama lengkapnya adalah vanessa heriyanto
Nama depannya adalah VANESSA
Nama belakang adalah HERIYANTO
('VANESSA', 'HERIYANTO')


In [16]:
#CONTOH 2
#contoh fungsi sederhana dengan nama hello_world
def halo_dunia ():
    print ('Halo phyton!Halo dunia!')

#kcukup mengetikan nama fungsinya, ditambahkan dengan tanda kurung biasa, maka fungsi akan terpanggil
#bahkan kita bisa memanggil fungsi halo_dunia berkali-kali
halo_dunia()
halo_dunia()
halo_dunia()

Halo phyton!Halo dunia!
Halo phyton!Halo dunia!
Halo phyton!Halo dunia!


In [23]:
#CONTOH 3

def selamat_datang(nama):
    print (f'Halo {nama}, selamat dataaang!')

#Kita juga dapat memanggil fungsi dan mengisi dengan variabel yang berbeda-beda sekaligus
selamat_datang ('Sam')  
selamat_datang ('Vanessa')
selamat_datang ('Galuh')

Halo Sam, selamat dataaang!
Halo Vanessa, selamat dataaang!
Halo Galuh, selamat dataaang!


In [29]:
#CONTOH 4 (PARAMETER WAJIB)
def perkenalan (nama,asal):
    print (f'Perkenalkan saya adalah {nama} dari {asal}')
    
perkenalan ("Vanessa","Surabaya")  #kita panggil fungsinya dengan mengisi variabel kosong tsb
perkenalan ('Tiwik','Bali') #pengisian variabel dengan nama dan asal yang berbeda

#jika hanya mengisi 1  variabel saja, contoh, hanya mengisi variabel nama, maka akan mendapatkan error

Perkenalkan saya adalah Vanessa dari Surabaya
Perkenalkan saya adalah Tiwik dari Bali


In [35]:
#CONTOH 5 (PARAMETER OPSIONAL)
#adalah parameteryang seandainya tidak diisi pun, dia sudah memiliki nilai defaultnya.
def suhu_udara (daerah, derajat, satuan='celcius'): #parameter daerah dan derajat adalah wajib, sedangkan satuan tidak,
                                                #karena sudah memiliki nilai default yaitu celcius
    print (f'Suhu di {daerah} adalah {derajat} {satuan}')
    
#pemanggilan fungsinya
suhu_udara ('bali', 49,'fahrenheit')  #pemanggilan 3 parameter yang dimana salah satunya bersifat opsional
#pemanggilan 2 fungsi yang wajib
suhu_udara ('surabaya',100)#tidak menuliskan nilai parameter ke3 pun tidak akan error dan
                            #akan diisi dengan nilai default.

Suhu di bali adalah 49 fahrenheit
Suhu di surabaya adalah 100 celcius


In [39]:
#CONTOH 6 (FUNGSI DENGAN PARAMETER TIDAK BERURUT)
#percobaan lanjutan dari sebelumnya, bagaiamana jika parameter opsionalnya ada lebih dari 1?
def suhu_udara (daerah, derajat=30, satuan='celcius'): #kita menentukan nilai default unruk derajat
    print (f'Suhu di {daerah} adalah {derajat} {satuan}')

#pemanggilan dengan 2 parameter:
suhu_udara('Jakarta','Fahrenheit')  #saat ingin mengisi daerah dan satuan, yang terisi malah daerah dan derajat.
#dapat diatasi sbb
suhu_udara ('Jakarta',satuan='Fahrenheit') #sudah sesuai dengankeinginan sebelumnya untuk hanya mengisi daerah dan satuan

#bahkan kita dapat memanggilnya secara tidak berurutan sekalipun,
suhu_udara (satuan='kelvin',daerah='malaysia',derajat=50) #hasilnya akan berurutan jika diberikan keterangan terlebih dahulu

Suhu di Jakarta adalah Fahrenheit celcius
Suhu di Jakarta adalah 30 Fahrenheit
Suhu di malaysia adalah 50 kelvin


In [55]:
#CONTOH 7 (FUNGSI MENGEMBALIKAN NILAI)
def luas_persegi (sisi):
    return sisi*sisi  #return berfungsi untuk mengembalikan nilai

#panggil fungsi :
print (luas_persegi(6)) #akan mengalikan 6 dengan 6 sesuai pengoperasian yang dideklarasikan
print (luas_persegi (10))#akan mengalikan 10 dengan 10 sesuai pengoperasian yang dideklarasikan

#diberi kalimat tambahan:
print ('Luas ppersegi dengan sisi (76) adalah ', luas_persegi (76))
#akan mengalikan 76 dengan 76 sesuai pengoperasian yang dideklarasikan

#kita juga dapat menyimpan di variabel:
persegi_besar= luas_persegi (101)
persegi_mungil= luas_persegi(2)
print ('Total kedua luas persegi besar dan mungil adalah ',persegi_besar+persegi_mungil) 

#LEBIH DARI 1 RETURN
#jika return telah dieksekusi pada sebuah fungsi, proses yang ada dalam blok kode fungsi akan berhenti
def persentase (total, jumlah):
    if (total>=0 and total<= jumlah):
        return total/jumlah*45 #jika memenuhi, maka akan menjalankan return ini dan skip semua perintah di bawahnya
    return False #ika tidak memenuhi, maka hasil outputnya False

#panggil fungsinya
print (persentase (30,50))
print (persentase (15,65))
print (persentase (100,60)) #return telah dieksekusi maka 

36
100
Luas ppersegi dengan sisi (76) adalah  5776
Total kedua luas persegi besar dan mungil adalah  10205
27.0
10.384615384615385
False


In [3]:
#CONTOH 8 (RUANG LINGKUP VARIABEL PADA FUNGSI)
#contoh variabel lokal, varaiabel yang hanya hidup dalam satu blok kode tertentu
#contohnya adalah sbb
kota= 'denpasar'
def halo():
    print (kota) 
    
#panggil fungsi
print ('[print secara langsung]', kota)   #langsung memanggil secara langsung yaitu 'kota'
print ('[panggil fungsi halo]', end=' ')  #memanggil fungsinya, yaitu fungsi halo ()
halo()

#variabel kota yang ada dalam fungsi adalah variabel kota yang sama dengan yang ada di luar fungsi

[print secara langsung] denpasar
[panggil fungsi halo] denpasar


In [65]:
#CONTOH 9
#coba diubah kode programnya:
kota, provinsi= 'denpasar','bali'
def halo():
    provinsi= 'bali'  #ubah variabel provinsi pada fungsi hello ()
    print (kota, provinsi)
#panggil fungsi
print ('[PANGGIL FUNGSI HALO ()]') #saat fungsi hello() dieksekusi, benar bahwa variabel provinsi berubah menjadi 'Jawa barat'
halo()

print ('\n [SECARA LANGSUNG]') #tetapi ketika ditampilkan lagi secara langsung variabel provinsi kembali ke nilai semula
print (kota, provinsi)

#pada saat mengubah variabel provinsi pada fungsi hello(), itu sebenarnya tidak merubah provinsi yang ada di luar,
#melainkan membuat variabel baru dengan nama sama, akan ttp hanya variabel lokal yang bisa mengakses yaitu fungsi hello ()

[PANGGIL FUNGSI HALO ()]
denpasar bali

 [SECARA LANGSUNG]
denpasar bali


In [9]:
#CONTOH 10 (DOCSTRING)
#kita bisa memberikan sebuah deskripsi terhadap fungsi yang kita buat.
#untuk mendiskripsikan deskripsi program, kita dapat menuliskan komentar multibaris tepat setelah mendefinisikan nam fungsi

def suhu_udara (daerah, derajat=30,satuan='celcius'):
    """
fungsi ini bertugas untuk menampilkan teks yang memberikan informasi tentang suhu udara di suatu daerah.
    """
print ("Suhu di {} adalah {} {}".format (daerah, derajat, satuan))



# 5.19.1 TUGAS FUNGSI PHYTON

In [ ]:
Ada dua jenis tugas fungsi pada Phyton:
    -Menjalankan perintah
    -Menampilkan hasil perhitungan

In [13]:
#CONTOH 1
def waktu_sampai(jarak,kecepatan): #deklarasi fungsi waktu_sampai ()
    waktu=jarak/kecepatan #menulis rumus waktu
    print (waktu)
waktu_sampai(80,60)  #mencetak waktu jika jarak=80, kecepatan=60

#kita dapat menuliskan nilainya dalam sebuah variabel a
a=waktu_sampai (80,60)
print (a)

1.3333333333333333
1.3333333333333333
None


In [12]:
def waktu_tempuh (jarak,kecepatan): 
    waktu=jarak/kecepatan  #menulis rumus dari waktu
    return (waktu)
waktu_tempuh(80,60)

#kita dapat menuliskan nilai waktu tempuh dalam variabel b
b=waktu_tempuh (80,60)
print (b)

1.3333333333333333


In [14]:
import numpy #jika tidak error saat dijalankan, maka artinya library sudah didownload

#untuk membuat sebuah alias gunakan keyword 'as' selagi mengimport:
import numpy as np 
#sekarang kita dapat merujuk numpy dengan hanya menuliskan np saja

In [11]:
import numpy as np    
print (np.__version__)  

1.21.5


In [13]:
import numpy
arr= numpy.array ([1,2,3,4,5])
print (arr) 

print (type(arr))  #arr merujuk pada ndarray, yaitu objek array pada numpy


#gunakan sebuah tuple untuk membuat sebuah numpy array:
arr=np.array ((1,2,3,4,5))
print (arr)

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
#MENGAPLIKASIKAN TUGAS FUNGSI PHYTON PADA RUMUS MATEMATIKA:

#RUMUS LUAS SEGITIGA
def luas_segitiga (alas, tinggi): #luas segitiga membutuhkan 2 parameter, yaitu alas dan tinggi
    luas_segitiga=(1/2)*alas*tinggi #deklarasikan rumus dari luas segitiga
    return luas_segitiga
print (luas_segitiga (5,2))  #memanggil fungsinya dan memberikan nilai alas=5 daan tinggi=2


#RUMUS LUAS LINGKARAN
def luas_lingkaran (jari_jari):  #luas lingkaran hanya membutuhkan 1 parameter, yaitu jari-jari
    luas_lingkaran= (22/7)*(jari_jari**2) #deklarasikan rumus luas lingkaran
    return luas_lingkaran
print (luas_lingkaran (14)) #memanggil fungsi dan memberikan nilai jari-jari sebesar 14

#RUMUS LUAS PERSEGI
def luas_persegi (sisi): #luas persegi hanya membutuhkan 1 parameter, yaitu jari-jari
    luas_persegi=sisi**2 #deklarasikan rumus luas persegi
    return luas_persegi
print (luas_persegi (2)) #memanggil fungsi dan memberikan nilai sisi sebesar 2

#RUMUS LUAS PERSEGI PANJANG
def luas_persegi_panjang (panjang, lebar): #luas lingkaran membutuhkan 2 parameter, yaitu panjang dan lebar
    luas=panjang*lebar  #deklarasikan rumus luas persegi panjang
    return luas
print(luas_persegi_panjang (2,3)) #memanggil fungsi dan memberikan nilai panjang=2 dan lebar=3

5.0
616.0
4
6


In [5]:
#saya memanggil kembali fungsi def() berbagai rumus agar menjadi satu kode block dengan kode yang akan saya buat
#karena pada saat saya tidak menjadikannya ke dalam satu kode blok yang sama, luas tidak terdefine

def luas_segitiga (alas, tinggi): #luas segitiga membutuhkan 2 parameter, yaitu alas dan tinggi
    luas_segitiga=(1/2)*alas*tinggi #deklarasikan rumus dari luas segitiga
    return luas_segitiga
def luas_lingkaran (jari_jari):  #luas lingkaran hanya membutuhkan 1 parameter, yaitu jari-jari
    luas_lingkaran= (22/7)*(jari_jari**2) #deklarasikan rumus luas lingkaran
    return luas_lingkaran
def luas_persegi (sisi): #luas persegi hanya membutuhkan 1 parameter, yaitu jari-jari
    luas_persegi=sisi**2 #deklarasikan rumus luas persegi
    return luas_persegi
def luas_persegi_panjang (panjang, lebar): #luas lingkaran membutuhkan 2 parameter, yaitu panjang dan lebar
    luas=panjang*lebar  #deklarasikan rumus luas persegi panjang
    return luas

jenis_bidang= input ('Tulis jenis bidang= ')
if jenis_bidang.upper ()=='SEGITIGA': 
    alas=float (input ('Berapakah panjang alas?')) #input parameter
    tinggi= float (input ('Berapakah tingginya?')) #input parameter2
    luas= luas_segitiga(alas, tinggi)  #Untuk menghitung luas segitiga, panggil fungsi def luas segitiga()
    print (f"Luas {jenis_bidang} adalah {luas}")
    
elif jenis_bidang.upper()=='LINGKARAN':
    jari_jari=float (input ('Berapakah panjang jari-jari?'))#input parameter
    luas=luas_lingkaran (jari_jari) #Untuk menghitung luas lingkaran, panggil fungsi def luas lingkaran()
    print (f"Luas {jenis_bidang} adalah {luas}")
    
elif jenis_bidang.upper()== 'PERSEGI' or (jenis_bidang.upper()=='BUJUR SANGKAR'):
    sisi= float (input('Berapa sisinya?')) #input parameter
    luas=luas_persegi(sisi)  #Untuk menghitung luas persegi atau bujur sangkar, panggil fungsi def luas persegi()
    print(f'Luas {jenis_bidang} adalah {luas}')
    
elif jenis_bidang.upper()=='PERSEGI PANJANG':
    panjang=float (input ('Berapakah panjangnya?'))#input parameter
    lebar=float(input('Berapakah lebarnya?'))#input parameter2
    luas=luas_persegi_panjang (panjang, lebar)  #Untuk menghitung luas persegi panjang, panggil fungsi def luas persegi panjang()
    print (f"Luas {jenis_bidang} adalah {luas}")
else:
    print (f'Maaf jenis bidang yang anda input tidak termasuk segitiga, lingkaran, persegi ataupun persegi panjang')
    print (f'Silahkan mencoba kembali')


Tulis jenis bidang= se
Maaf jenis bidang yang anda input tidak termasuk segitiga, lingkaran, persegi ataupun persegi panjang
Silahkan mencoba kembali


# 5.20 NUMPY

In [4]:
#Numpy adalah library phyton yang digunakan dengan array.
#Berfungsi untuk beekerja dalam domain aljabar linear, matrix dan lain-lain

In [6]:
import pandas as pd

### 5.20.1 perintah dasar numpy

In [ ]:
Numpy arrays menyediakan atribut ndim yang mengembalikan bilangan bulat yang memberi tahu kita
berapa banyak dimensi yang dimiliki array.

In [83]:
#CONTOH 1
import numpy as np
a=np.array ([0,1,2,3,4])
print (a)  #cetak array a

b=np.array ([[5,6,7,8],[9,8,7,6]])
print (b)  #cetak array b

c=np.array ([[[0,1,2,3],[4,5,6,7]],  #ketika diberi kurung siku sebanyak 2 kali, maka akan ter-enter
           [[8,9,8,7],[6,5,4,3]],
           [[1,2,3,4],[5,6,7,8]]])
print (c)  #cetak array c


print (a.ndim)
print (a.ndim)
print (a.ndim)

print (a.shape)
print (a.shape)
print (a.shape)


[0 1 2 3 4]
[[5 6 7 8]
 [9 8 7 6]]
[[[0 1 2 3]
  [4 5 6 7]]

 [[8 9 8 7]
  [6 5 4 3]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [12]:
#CONTOH 2 (mengecek dimensi dari array)
import numpy as np

a=np.array (42) 
b=np.array ([1,2,3,4,5]) #berdimensi 1 saat memiliki 1 kurung di awal dan di akhir
c=np.array ([[1,2,3],[4,5,6]]) #berdimensi 2 saat memiliki 2 kurung di awal dan di akhir
d=np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]]) #berdimensi 3 saat memiliki 3 kurung di awal dan di akhir
print (a.ndim)
print (b.ndim)
print (c.ndim)
print (d.ndim)

0
1
2
3


In [13]:
#DIMENSI LEBIH TINGGI PADA ARRAY
#kita dapat menentukan jumlah dimensi dengan menggunakan argumen ndmin

import numpy as np
arr=np.array ([1,2,3,4],ndmin=5)
print (arr)
print ('number of dimensions: ', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions:  5


### memanggil anggota, kolom dan baris dengan numpy

In [25]:
import numpy as np
d= np.array ([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print (d)

print (d[0,3]) #mencetak elemen baris ke0 kolom ke3
print (d[ : ]) #mencetak semua elemen yang ada
print (d[1: ]) #mencetak semua elemen dari baris ke-1 sampai selesai
print (d[:,2]) #mencetak semua elemen dari awal sampai baris ke2
print (d[0,1:3]) #mencetak semua elemen dari baris ke0 hingga baris ke3 namun dengan jarak 3 lompatan
print (d[0,0:3:2]) 

#update nilai dari elemen baris ke0 kolom ke0 dengan angka 100
d[0,0]=100
print (d)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[ 3  7 11]
[2 3]
[1 3]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


### matriks pada numpy

In [14]:
import numpy as np
print (np.ones ((2,3))) #membuat array matriks dengan ukuran 2 x 3 yang semua elemen diisi dengan angka 1
print (np.ones ((2,2)))  #membuat array matriks dengan ukuran 2 x 2 yang semua elemen diisi dengan angka 1

print (np.zeros ((3,2)))  #membuat array matriks dengan ukuran 3 x 2 yang semua elemen diisi dengan angka 0
print (np.identity(4))  #membuat array matriks identitas dengan ukuran 4 x 4 
print (np.ones ((2,3,4)))  #membuat array matriks dengan ukuran 3 x 4 yang semua elemen diisi dengan angka 1

print (np.full((3,2),9))  #membuat array matriks dengan ukuran 3 x 2 yang semua elemen diisi dengan angka 9
print (np.full ((3,2),2)) #membuat array matriks dengan ukuran 3 x 2 yang semua elemen diisi dengan angka 2
print (np.full ((3,2),-1)) #membuat array matriks dengan ukuran 3 x 2 yang semua elemen diisi dengan angka negatif yaitu -1

print (np.random.rand(4,3))  #membuat array matriks dengan ukuran 4 x 3 yang semua elemen diisi dengan random
print (np.random.randint(1,10,size=(3,4)))  #membuat array matriks dengan ukuran 3 x 4 yang semua elemen diisi dengan angka 
                                            #random anntara 1-10
print (np.random.rand(1,1)) #membuat array matriks 1 x 1 elemen diisi dengan angka random

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[9 9]
 [9 9]
 [9 9]]
[[2 2]
 [2 2]
 [2 2]]
[[-1 -1]
 [-1 -1]
 [-1 -1]]
[[0.79101388 0.73159475 0.43548145]
 [0.36993806 0.53962904 0.65580848]
 [0.72812101 0.07950765 0.36529656]
 [0.360683   0.89057869 0.83959957]]
[[8 4 9 2]
 [7 7 9 9]
 [3 6 2 6]]
[[0.21683582]]


### Buatlah matriks ukuran 10 x 10 dengan menggunakan Numpy

In [21]:
#Jawaban:

a=np.zeros ((10,10)) #pertama, buat matriks elemen 0 dengan ukuran 10x10
print (a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [22]:
b=np.identity(10) #buat matriks identitas dengan ukuran 10x10
print (b)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [23]:
c=9*b  #mengalikan matriks b dengan angka 9, sehingga angka 1 di matriks b berubah menjadi 9
print (c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 9. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 9. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 9. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 9. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 9. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 9. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [26]:
d=np.ones((8,8)) #membuat matriks berelemen 1 berukuran 8x8
e=np.identity (8)*8 #membuat matriks identitas berukuran 8 kali 8 lalu dikali dengan konstanta 8, sehingga angka 1 berubah jd 8
f=d+e #matriks f adalah penjumlahan dari matriks d dan e
print (d)
print (e)
print (f)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[8. 0. 0. 0. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0. 0. 0. 0.]
 [0. 0. 8. 0. 0. 0. 0. 0.]
 [0. 0. 0. 8. 0. 0. 0. 0.]
 [0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 0. 0. 0. 0. 8. 0. 0.]
 [0. 0. 0. 0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 8.]]
[[9. 1. 1. 1. 1. 1. 1. 1.]
 [1. 9. 1. 1. 1. 1. 1. 1.]
 [1. 1. 9. 1. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 1. 9. 1. 1. 1.]
 [1. 1. 1. 1. 1. 9. 1. 1.]
 [1. 1. 1. 1. 1. 1. 9. 1.]
 [1. 1. 1. 1. 1. 1. 1. 9.]]


In [35]:
c[1:-1,1:-1]=f
print (c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 9. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 9. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 9. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 9. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [33]:
g=np.identity (6)*9 #buat matriks identitas 6x6 dan dikali dengan konstanta 9, sehingga 1 menjadi 9
c[2:-2,2:-2]=g
print (g)
print (c)

[[9. 0. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0. 0.]
 [0. 0. 9. 0. 0. 0.]
 [0. 0. 0. 9. 0. 0.]
 [0. 0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 0. 9.]]
[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 9. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 9. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [30]:
h=np.ones ((4,4))*2 #buat matriks elemen 1 4x4 dan dikali dengan konstanta 2, sehingga 1 menjadi 2
i=np.identity(4)*7 #buat matriks identitas 4x4 dan dikali dengan konstanta 7, sehingga 1 menjadi 7
j=h+i #matriks j adalah penjumlahan matriks h dan matriks i
print (h)
print (i)
print (j)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[7. 0. 0. 0.]
 [0. 7. 0. 0.]
 [0. 0. 7. 0.]
 [0. 0. 0. 7.]]
[[9. 2. 2. 2.]
 [2. 9. 2. 2.]
 [2. 2. 9. 2.]
 [2. 2. 2. 9.]]


In [31]:
c[3:-3,3:-3]=j
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 2. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 9. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 9. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 2. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [32]:
k=np.identity (2)*9
c[4:-4,4:-4]=k
print (c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 2. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 9. 0. 2. 0. 1. 0.]
 [0. 1. 0. 2. 0. 9. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 2. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


### copy pada numpy

In [ ]:
Untuk menghindari perubahan variabel awal yang tidak dikehendaki, maka diperlukan perintah copy pada numpy sbb

In [36]:
import numpy as np

#CONTOH YANG SALAH
a=np.array([1,2,3,4,5])  #misalkan terdapat array a yang berisikan 12345
print (a)

b=a  #matriks b=matriks a
print (b)

b[0]=10 #sehingga pada saat ingin mengubah suatu elemen di array b, elemen pada array a juga akan berubah
print (b)

print (a) #karena belum dicopy terlebih dahulu

[1 2 3 4 5]


In [44]:
#CONTOH YANG BENAR
c=np.array([1,2,3,4,5]) #misalkan terdapat array a yang berisikan 12345
print (c)

d=c.copy () #matriks d adalah copy dari matriks c
print (d)

d[0]=10 #sehingga pada saat ingin mengubah suatu elemen di array d, elemen pada array c tidak akan ikut berubah
print (d)

print (c)

[1 2 3 4 5]
[1 2 3 4 5]
[10  2  3  4  5]
[1 2 3 4 5]


### 5.20.5 operasi matematika pada numpy

In [49]:
#CONTOH 1
a=np.array ([0,1,2,3,4,5])
print (a+2) #tiap elemen di array a dijumlahkan dengan 2
print (a-2)#tiap elemen di array a dikurangkan dengan 2
print (a*2) #tiap elemen di array a dikalikan dengan 2
print (a/2) #tiap elemen di array a dibagi dengan 2
print (a**2) #tiap elemen di array a dipangkatkan dengan 2

[2 3 4 5 6 7]
[-2 -1  0  1  2  3]
[ 0  2  4  6  8 10]
[0.  0.5 1.  1.5 2.  2.5]
[ 0  1  4  9 16 25]


In [53]:
#CONTOH 2
b=np.array ([6,7,8,9,10,11])
print (b)
print (a+b) #menjumlahkan array a dan b di tiap elemen yang sesuai
print (a-b) #mengurangkann array a dan b di tiap elemen yang sesuai
print (a*b) ##mengalikan array a dan b di tiap elemen yang sesuai
print (a/b) ##membagi array a dan b di tiap elemen yang sesui
print (b**a) #memangkatkan tiap elemen b dengan a di tiap elemen yang sesuai

[ 6  7  8  9 10 11]
[ 6  8 10 12 14 16]
[-6 -6 -6 -6 -6 -6]
[ 0  7 16 27 40 55]
[0.         0.14285714 0.25       0.33333333 0.4        0.45454545]
[     1      7     64    729  10000 161051]


In [18]:
#CONTOH 3
arr_29= np.array ([1,2,3,4,5])
arr_29_2=np.array ([2,2,2,2,2])

#operasi matematika berupa tambah +, kurang -,kali *,bagi /,dan pangkat **
print ("Penjumlahan = ", arr_29+arr_29_2)
print ("Pengurangan = ", arr_29-arr_29_2)
print ("Perkalian = ", arr_29*arr_29_2)
print ("Pembagian = ", arr_29/arr_29_2)
print ("Perpangkatan = ", arr_29**arr_29_2)

Penjumlahan =  [3 4 5 6 7]
Pengurangan =  [-1  0  1  2  3]
Perkalian =  [ 2  4  6  8 10]
Pembagian =  [0.5 1.  1.5 2.  2.5]
Perpangkatan =  [ 1  4  9 16 25]


In [24]:
#OPERASI MENGGUNAKAN SIN COS TAN
print (np.cos(a))
print (np.cos (b))
print (np.cos (a+b))#menambahkan array a dan b dalam fungsi cos

print (np.tan (a))
print (np.tan (a-b)) #mengurangkan array a dan b dalam fungsi tan

print (np.sin(a))
print (np.sinh (a))
print (np.sinh(a/b)) #membagi array a dan b dalam fungsi sinh

print (np.cosh (a))
print (np.cosh (a*2))#mengalikan array a dengan 2 dalam fungsi cosh

print (np.tanh(a))
print (np.tanh(a-b))#mengurangkan array a dan b dalam fungsi tanh

print (np.sqrt(a)) #menghitung akar kuadrat

-0.39998531498835127
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 0.5551133   0.99984331  0.52532199 -0.43217794 -0.99233547]
2.2913879924374863
[ 0.1606567  -1.11721493  3.61455441  0.31030966 -0.84077126]
-0.9165215479156338
8.696374707602505e+17
[8.69637471e+17 6.59407867e+08 6.01302142e+05 1.81577513e+04
 2.22353326e+03]
8.696374707602505e+17
1.5125386611005713e+36
1.0
[1. 1. 1. 1. 1.]
6.48074069840786


In [30]:
#menemukan sudut dari fungsi trigonometri
#soal: temukan sudut tan 1,0
    
import numpy as np
x=np.arctan(1.0)
print (x)

0.7853981633974483


In [27]:
#CONTOH LAIN (mengubah nilai array berikut menjadi radian)
import numpy as np
x=np.cos(np.pi/3)
print (x)

#konversi array menjadi radian
arr=np.array ([90,180,270,360])
x=np.deg2rad(arr)
print (x)

#konversi radian menjadi derajat
arr=np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x=np.rad2deg(arr)
print (x)

0.5000000000000001
[1.57079633 3.14159265 4.71238898 6.28318531]
[ 90. 180. 270. 360.]


### perkalian matriks pada numpy

In [ ]:
Perkalian matriks pada Numpy menggunakan perintah matmul.
Kita perlu memerhatikan tentang ukuran matriks yang akan dikalikan. 
Contoh, matriks 2x3 dapat dikalikan dengan matriks 3x4

In [70]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print (a)

b=np.array ([[9,10,11,12],[13,14,15,16]])
print (b)

c=a*b  #matriks c adalah perkalian matriks a dan b
        #perkalian kedua matriks dapat dilakukan karena matriks a dan matriks b memenuhi ukuran matriks yang sesuai
print (c)


e=np.array([[9,10],[11,12],[13,14],[15,16]])
print (e)

h=np.array ([[1,2],[3,4],[5,6],[7,8]])

f=np.matmul (a,e)
print (f)

g=h*e  #perkalian matriks (4,2) dan (4,2)
print (g)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[  9  20  33  48]
 [ 65  84 105 128]]
[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]
[[130 140]
 [322 348]]
[[  9  20]
 [ 33  48]
 [ 65  84]
 [105 128]]


### min, max dan sum pada numpy

Perintah min, max dan sum digunakan untuk mengetahui nilai minimum, maksimum, dan penjumlahan

In [76]:
a=np.array([[1,2,3,4],
            [5,6,7,8],
           [9,10,11,12]])
print (a)  #mencetak array a

b=np.min(a)  #mencari tahu nilai minimum pada array b, yaitu 1
print (b)

c=np.min (a,axis=0)  #mencari tahu nilai minimum pada array a, pada sumbu x atau kolom
print (c)

d=np.min (a,axis=1) #mencari tahu nilai minimum pada array a, pada sumbu y atau baris
print (d)

e=np.max (a)  #mencari tahu nilai maksimal yang ada di dalam array a
print (e)

f=np.max (a,axis=0) #mencari nilai kolom yang maksimal dari kolom-kolom yang lain
print (f)

g=np.max(a,axis=1) #mencari nilai max axis pada kolom (baris ke bawah), yang paling besar adalah kolom terakhir yaitu
                    #kolom yang berisi 4, 8, 12
print (g)

h=np.sum (a)  #menjumlahkan semua elemen pada array a
print (h)

h=np.sum (a,axis=0) #menjumlahkan nilai elemen a pada setiap kolom
print (h)           

i=np.sum(a,axis=1) #menjumlahkan nilai elemen a pada setiap barisnya
print (i)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[1 2 3 4]
[1 5 9]
12
[ 9 10 11 12]
[ 4  8 12]
78
[15 18 21 24]
[10 26 42]


# DIMENSI PADA ARRAY

In [80]:
#dimensi pada array
#dimensi dalam array adalah satu tingkat kedalaman array (array bersarang)


#membuat 0-D array dengan nilai 42
import numpy as np
arr = np.array (42)
print (arr)

#membuat 1-D array yang mengandung nilai 1,2,3,4,5
#adalah array yang paling umum dan dasar
import numpy as np
arr=np.array ([1,2,3,4,5])
print (arr)

#2-D array adalah sebuah array yang memiliki 1-D sebagai elemennya,sering digunakan untuk merepresentasikan matriks
#membuat 2-D array yang mengandung dua array dengan nilai 1,2,3 dan 4,5,dan 6:
import numpy as np
arr=np.array ([[1,2,3],[4,5,6]])
print (arr)

#3-D array adalah array yang memiliki 2-D sebagai elemennya, biasa digunakan tensor ke-3
#membuat 3-D array dengan nilai 1,2,3 dan 4,5,6:
import numpy as np 
arr= np.array ([[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]])
print (arr)

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


## TAMBAHAN 

In [28]:
#MENGECEK TIPE DATA ARRAY
import numpy as np
arr=np.array ([[1,2,3],[4,5,6]])
print (type (arr))

<class 'numpy.ndarray'>
